# -*- coding: utf-8 -*-
"""computer-vision.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16vqgmnRBkTU51HBeE8ST47Xm1t6JParA
"""

import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import tensorflow_hub as hub
print('TensorFlow version:', tf.__version__)
print('TensorFlow Hub version:', hub.__version__)

model_name = 'efficientnetv2-b2-21k'

models_path = {
    "efficientnetv2-b2-21k": "https://tfhub.dev/google/imagenet/efficientnet_v2_imagenet21k_b2/feature_vector/2",
}

models_pixels = {
    "efficientnetv2-b2-21k": 260
}

model_path = models_path.get(model_name)
model_path

pixels = models_pixels.get(model_name)
pixels

image_size = (pixels, pixels)
image_size

print('Model: ', model_name)
print('Path: ', model_path)
print('Imagem size: ', image_size)

data_directory = 'https://github.com/Paimonz/computer-vision/tree/cfe3cd663c3932f00efa4dc7894b8312875446ae/dataset', line = True

data_directory = tf.keras.utils.get_file('eye-diseases-classification',
                                         'https://www.kaggle.com/datasets/gunavenkatdoddi/eye-diseases-classification',
                                         untar = True)

from google.colab import drive
drive.mount('/content/drive')

train_dataset = tf.keras.preprocessing.image_dataset_from_directory(data_directory,
                                                                    validation_split= .20,
                                                                    subset = 'training',
                                                                    label_mode='categorical',
                                                                    seed = 123,
                                                                    image_size=image_size,
                                                                    batch_size=1)