# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16vqgmnRBkTU51HBeE8ST47Xm1t6JParA
"""

import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import tensorflow_hub as hub
print('TensorFlow version:', tf.__version__)
print('TensorFlow Hub version:', hub.__version__)

model_name = 'efficientnetv2-xl-21k-ft1k'

models_path = {
    "efficientnetv2-xl-21k-ft1k": "https://tfhub.dev/google/imagenet/efficientnet_v2_imagenet21k_ft1k_xl/feature_vector/2",
}

models_pixels = {
    "efficientnetv2-xl-21k-ft1k": 512
}

model_path = models_path.get(model_name)
model_path

pixels = models_pixels.get(model_name)
pixels

image_size = (pixels, pixels)
image_size

print('Model: ', model_name)
print('Path: ', model_path)
print('Imagem size: ', image_size)

data_directory = tf.keras.utils.get_file('Imagensolhos',
                                         'https://github.com/Paimonz/computer-vision/tree/main/Imagensolhos',
                                         )

train_dataset = tf.keras.preprocessing.image_dataset_from_directory(data_directory,
                                                                    validation_split= .20,
                                                                    subset = 'training',
                                                                    label_mode='categorical',
                                                                    seed = 123,
                                                                    image_size=image_size,
                                                                    batch_size=1)